// Copyright (c) 2026 Jose Antonio Escribano joseantonioescribanoayllon@gmail.com

#include "World/DemoGridTerrain.h"

#include <algorithm>
#include <random>

DemoGridTerrain::DemoGridTerrain(
    const int inWidth,
    const int inHeight,
    const std::uint32_t inSeed,
    const std::size_t inInteractableCount)
    : mWidth(std::max(1, inWidth))
    , mHeight(std::max(1, inHeight))
    , mCells(static_cast<std::size_t>(mWidth * mHeight), DemoGridCellType::Walkable)
{
    BuildRandomTerrain(inSeed);
    GenerateInteractables(inSeed ^ 0x6C8E9CF5u, inInteractableCount);
}

bool DemoGridTerrain::IsInside(const Cell& inCell) const
{
    return inCell.X >= 0 && inCell.X < mWidth &&
           inCell.Y >= 0 && inCell.Y < mHeight;
}

DemoGridCellType DemoGridTerrain::GetCellType(const Cell& inCell) const
{
    if (!IsInside(inCell))
        return DemoGridCellType::Blocked;

    return mCells[ToIndex(inCell)];
}

bool DemoGridTerrain::IsBlocked(const Cell& inCell) const
{
    return GetCellType(inCell) == DemoGridCellType::Blocked;
}

bool DemoGridTerrain::IsInteractable(const Cell& inCell) const
{
    return GetCellType(inCell) == DemoGridCellType::Interactable;
}

const DemoGridInteractable* DemoGridTerrain::GetInteractableAt(const Cell& inCell) const
{
    for (const DemoGridInteractable& Interactable : mInteractables)
    {
        if (Interactable.Location == inCell)
            return &Interactable;
    }

    return nullptr;
}

const char* DemoGridTerrain::GetInteractableTypeName(const DemoGridInteractableType inType)
{
    switch (inType)
    {
    case DemoGridInteractableType::Viewpoint:
        return "Viewpoint";
    case DemoGridInteractableType::Bench:
        return "Bench";
    case DemoGridInteractableType::ShopWindow:
        return "Shop window";
    }

    return "Interactable";
}

std::size_t DemoGridTerrain::ToIndex(const Cell& inCell) const
{
    return static_cast<std::size_t>(inCell.Y * mWidth + inCell.X);
}

void DemoGridTerrain::SetCellType(const Cell& inCell, const DemoGridCellType inType)
{
    if (IsInside(inCell))
        mCells[ToIndex(inCell)] = inType;
}

void DemoGridTerrain::BuildRandomTerrain(const std::uint32_t inSeed)
{
    std::mt19937 Generator(inSeed);
    std::bernoulli_distribution IsBlockedCell(0.22);

    for (DemoGridCellType& CellType : mCells)
        CellType = IsBlockedCell(Generator) ? DemoGridCellType::Blocked : DemoGridCellType::Walkable;

    // Keep the border traversable. The current Wanderer route uses the border
    // and this also provides a guaranteed fallback corridor around the map.
    for (int X = 0; X < mWidth; ++X)
    {
        SetCellType({X, 0}, DemoGridCellType::Walkable);
        SetCellType({X, mHeight - 1}, DemoGridCellType::Walkable);
    }

    for (int Y = 0; Y < mHeight; ++Y)
    {
        SetCellType({0, Y}, DemoGridCellType::Walkable);
        SetCellType({mWidth - 1, Y}, DemoGridCellType::Walkable);
    }
}

void DemoGridTerrain::GenerateInteractables(
    const std::uint32_t inSeed,
    const std::size_t inInteractableCount)
{
    struct InteractableDefinition
    {
        DemoGridInteractableType Type;
        const char* IdPrefix;
        const char* ContextAnimation;
        float UsageTimeSeconds;
    };

    static constexpr InteractableDefinition Definitions[] = {
        {DemoGridInteractableType::Viewpoint,  "viewpoint",   "look_at_view",       2.5f},
        {DemoGridInteractableType::Bench,      "bench",       "sit_on_bench",       4.0f},
        {DemoGridInteractableType::ShopWindow, "shop_window", "check_shop_window",  3.0f},
    };

    mInteractables.clear();
    if (inInteractableCount == 0u)
        return;

    // Build the candidate pool from cells generated by this terrain. The default
    // terrain dimensions are DefaultWidth x DefaultHeight, while custom terrain
    // sizes automatically use their own valid bounds. Blocked cells never enter
    // this list, so interactables cannot be spawned on inaccessible terrain.
    std::vector<Cell> AvailableCells;
    AvailableCells.reserve(static_cast<std::size_t>(mWidth * mHeight));

    for (int Y = 0; Y < mHeight; ++Y)
    {
        for (int X = 0; X < mWidth; ++X)
        {
            const Cell Candidate{X, Y};
            if (GetCellType(Candidate) == DemoGridCellType::Walkable)
                AvailableCells.push_back(Candidate);
        }
    }

    std::mt19937 Generator(inSeed);
    std::shuffle(AvailableCells.begin(), AvailableCells.end(), Generator);

    const std::size_t Count = std::min(inInteractableCount, AvailableCells.size());
    mInteractables.reserve(Count);

    std::uniform_int_distribution<std::size_t> DefinitionDistribution(
        0u,
        (sizeof(Definitions) / sizeof(Definitions[0])) - 1u);

    std::size_t TypeCounters[sizeof(Definitions) / sizeof(Definitions[0])] = {};

    for (std::size_t Index = 0; Index < Count; ++Index)
    {
        const std::size_t DefinitionIndex = DefinitionDistribution(Generator);
        const InteractableDefinition& Definition = Definitions[DefinitionIndex];
        const std::size_t TypeIndex = TypeCounters[DefinitionIndex]++;

        DemoGridInteractable Interactable;
        Interactable.Id = std::string(Definition.IdPrefix) + "_" + std::to_string(TypeIndex);
        Interactable.Type = Definition.Type;
        Interactable.Location = AvailableCells[Index];
        Interactable.ContextAnimation = Definition.ContextAnimation;
        Interactable.UsageTimeSeconds = Definition.UsageTimeSeconds;

        mInteractables.push_back(std::move(Interactable));
        SetCellType(AvailableCells[Index], DemoGridCellType::Interactable);
    }
}
