# Copyright (c) 2026 Jose Antonio Escribano. All rights reserved.
param([string]$OutputPath = "$PSScriptRoot/../docs/RUNTIME_BRIDGE_AUDIT.md")
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$bridge = Get-Content "$root/HTNFramework/src/Translator/HTNRuntimeBridge.h" -Raw
$entries = @([regex]::Matches($bridge, 'X\([^,]+,\s*((?:HTN|Htn)\w+),') | ForEach-Object { $_.Groups[1].Value })
$generator = Get-Content "$root/HTNFramework/src/Translator/HTNCCodeGenerator.cpp" -Raw
$headers = @('Core/HTNAtomC.h','Core/HtnSymbolGenerated.h','Translator/HTNCallTermBridge.h',
    'Translator/HTNGeneratedBacktracking.h','Translator/HTNGeneratedDebug.h',
    'Translator/HTNGeneratedProfiling.h','WorldState/HTNGeneratedWorldState.h','Translator/HTNGeneratedPlanner.h')
$rows = @()
$declared = @()
foreach ($header in $headers) {
    $text = Get-Content "$root/HTNFramework/src/$header" -Raw
    $text = [regex]::Replace($text, '(?s)/\*.*?\*/', '')
    $text = [regex]::Replace($text, '(?m)//[^\r\n]*', '')
    foreach ($match in [regex]::Matches($text, '(?m)^\s*(?:const\s+)?\w+\s*\*?\s+((?:HTN|Htn)\w+)\s*\([^;{}]*\)\s*;')) {
        $name = $match.Groups[1].Value
        $declared += $name
        $direct = $generator -match ('\b' + $name + '\s*\(')
        $present = $name -in $entries
        $use = if ($direct) { 'Generator reference' } elseif ($present) { 'Macro/runtime bridge surface' } else { 'Public host/helper API; not emitted by current generator' }
        if ($direct -and !$present) { throw "Generator function absent from bridge: $name" }
        $rows += "| $name | $header | $use | $(if ($present) { 'Yes' } else { 'No (not required by emitted C)' }) |"
    }
}
if ($rows.Count -lt 50) { throw 'Incomplete public function inventory' }
foreach ($name in $entries) {
    if ($name -notin $declared) { throw "Bridge entry has no inventoried public declaration: $name" }
}
$inlineHeader = Get-Content "$root/HTNFramework/src/Translator/HTNGeneratedPlanner.h" -Raw
foreach ($match in [regex]::Matches($generator, '\b((?:HTN|Htn)[A-Za-z0-9_]+)\s*\(')) {
    $name = $match.Groups[1].Value
    # HTN_ identifiers are generated macros (their external targets are inventoried
    # above); HTNBuildCompilerIR runs inside the C++ translator, not emitted C.
    if ($name.StartsWith('HTN_') -or $name -eq 'HTNBuildCompilerIR') { continue }
    if ($name -in $entries) { continue }
    if ($inlineHeader -match ('static inline[^{};]*\b' + $name + '\s*\(')) { continue }
    throw "Unclassified generator function reference: $name"
}
$text = @('# RuntimeBridge 2.0.2 function audit', '',
    'Generated by `SDK/AuditRuntimeBridge.ps1`. Declarations are inventoried independently of the bridge table.', '',
    '## Difference from 2.0.1', '',
    '- Required emitted functions missing in 2.0.1: `HTNAtom_SetInt`, `HTNAtom_SetFloat`.',
    '- Both are now in the existing canonical X-macro table, which drives fields, host assignment, binding checks, forwarding and exports.',
    '- No additional directly emitted external function was found missing in this inventory.',
    '- `HTNGeneratedVariables_Get` and `HTNGeneratedVariables_IsBound` are static inline helpers; generated macros expand to the debug/profiling table entries.',
    '- Functions listed as host/helper APIs are not promises of bridge exports. The object/export check is authoritative for actual emitted dependencies, including macro expansion and compiler optimizations.', '',
    '| Function | Declaration | Usage classification | Bridge entry |', '| --- | --- | --- | --- |') + ($rows | Sort-Object -Unique)
$text | Set-Content -LiteralPath $OutputPath -Encoding UTF8
Write-Host "PASS: $($rows.Count) declarations inventoried; $($entries.Count) conditional/unconditional bridge entries"
