cmake_minimum_required(VERSION 3.25)
if(TARGET HTN::HTNFramework)
    return()
endif()
if(NOT WIN32 OR NOT MSVC OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "This HTN SDK requires Windows x64 and an MSVC-compatible compiler")
endif()
get_filename_component(_htn_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(READ "${_htn_root}/manifest.json" _htn_manifest)
string(JSON HTN_VERSION GET "${_htn_manifest}" sdk_version)
set(_htn_configs ${CMAKE_CONFIGURATION_TYPES})
if(NOT _htn_configs)
    if(NOT CMAKE_BUILD_TYPE)
        message(FATAL_ERROR "Select CMAKE_BUILD_TYPE before finding HTN")
    endif()
    set(_htn_configs "${CMAKE_BUILD_TYPE}")
endif()
foreach(_component HTNFramework HTNIntegration)
    add_library(HTN::${_component} STATIC IMPORTED GLOBAL)
    set_target_properties(HTN::${_component} PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${_htn_root}/include/${_component}"
        INTERFACE_COMPILE_FEATURES cxx_std_20)
endforeach()
add_library(HTN::HTNRuntimeBridge SHARED IMPORTED GLOBAL)
set_target_properties(HTN::HTNRuntimeBridge PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${_htn_root}/include/HTNFramework")
add_executable(HTN::HTNTranslator IMPORTED GLOBAL)
set_property(TARGET HTN::HTNTranslator PROPERTY IMPORTED_LOCATION
    "${_htn_root}/bin/windows-x86_64/tools/HTNTranslator.exe")
string(JSON _htn_count LENGTH "${_htn_manifest}" variants)
math(EXPR _htn_last "${_htn_count} - 1")
foreach(_config IN LISTS _htn_configs)
    string(TOUPPER "${_config}" _upper)
    if(NOT DEFINED HTN_VARIANT_${_upper})
        if(_config STREQUAL "Debug")
            set(HTN_VARIANT_${_upper} DynamicDebugInstrumented)
        elseif(_config STREQUAL "Release" OR _config STREQUAL "RelWithDebInfo" OR _config STREQUAL "MinSizeRel")
            set(HTN_VARIANT_${_upper} DynamicReleasePlain)
        else()
            message(FATAL_ERROR "Set HTN_VARIANT_${_upper} to an HTN manifest variant id")
        endif()
    endif()
    set(_found FALSE)
    foreach(_index RANGE ${_htn_last})
        string(JSON _variant GET "${_htn_manifest}" variants ${_index})
        string(JSON _id GET "${_variant}" id)
        if(NOT _id STREQUAL HTN_VARIANT_${_upper})
            continue()
        endif()
        set(_found TRUE)
        string(JSON _runtime GET "${_variant}" msvc_runtime_library)
        string(JSON _defs_count LENGTH "${_variant}" defines)
        math(EXPR _defs_last "${_defs_count} - 1")
        set(_defs "")
        foreach(_def_index RANGE ${_defs_last})
            string(JSON _def GET "${_variant}" defines ${_def_index})
            list(APPEND _defs "${_def}")
        endforeach()
        foreach(_component HTNFramework HTNIntegration HTNRuntimeBridge)
            set_property(TARGET HTN::${_component} APPEND PROPERTY IMPORTED_CONFIGURATIONS "${_config}")
            if(_component STREQUAL "HTNRuntimeBridge")
                set_target_properties(HTN::${_component} PROPERTIES
                    IMPORTED_IMPLIB_${_upper} "${_htn_root}/lib/windows-x86_64/${_id}/${_component}.lib"
                    IMPORTED_LOCATION_${_upper} "${_htn_root}/bin/windows-x86_64/${_id}/${_component}.dll")
            else()
                set_property(TARGET HTN::${_component} PROPERTY IMPORTED_LOCATION_${_upper}
                    "${_htn_root}/lib/windows-x86_64/${_id}/${_component}.lib")
            endif()
            set_property(TARGET HTN::${_component} APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS "$<$<CONFIG:${_config}>:${_defs}>")
        endforeach()
        set_property(TARGET HTN::HTNFramework APPEND_STRING PROPERTY HTN_CONSUMER_RUNTIME "$<$<CONFIG:${_config}>:${_runtime}>")
        break()
    endforeach()
    if(NOT _found)
        message(FATAL_ERROR "Unknown HTN variant: ${HTN_VARIANT_${_upper}}")
    endif()
endforeach()
set_property(TARGET HTN::HTNIntegration PROPERTY INTERFACE_LINK_LIBRARIES HTN::HTNFramework)

# Apply to each client target, including targets compiling generated C domains.
function(htn_configure_target target)
    get_target_property(_runtime HTN::HTNFramework HTN_CONSUMER_RUNTIME)
    set_target_properties(${target} PROPERTIES MSVC_RUNTIME_LIBRARY "${_runtime}"
        CXX_STANDARD 20 CXX_STANDARD_REQUIRED YES C_STANDARD 11 C_STANDARD_REQUIRED YES)
endfunction()
